title: "Tom Workbook"
author: "Tom Tang"
# logo: logo.png  # Optional
# Repository URL (for GitHub Pages)
repository:
  url: "https://github.com/tomctang/wk"
  path_to_docs: "https://github.com/tomctang/wk"
  branch: "gh-pages"  # Deployment branch for GitHub Pages

# HTML and theme configuration
html:
  use_issues_button: false
  use_repository_button: true
  extra_css: ["_static/custom.css"]
#  favicon: "path/to/favicon.ico" 
#html:
#  theme:
#    name: "sphinx_book_theme"
#    options:
#      use_repository_button: true
#      body_max_width: "90%"  # Adjusts the width of the main content (default is "none")
#      font_size: "16px"      # Base font size (can also be set in custom CSS)
#      use_edit_page_button: true  # Adds "Edit this page" link
#      logo_only: true
#      search_bar_position: "navbar"
#      extra_navbar: '<p>My Custom Footer</p>'

# Sitemap (optional)
sitemap:
  filename: "sitemap.xml"
  base_url: "https://tomctang.github.io/wk/"
# Execution options
execute:
  execute_notebooks: "off"  # Change to "auto" to execute notebooks during build
# Enable MathJax for equations
#mathjax:
#  enable: true

# sphinx:
#   config:
#     html_js_files:
#       - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
#     mathjax3_config:
#       tex:
#         inlineMath: [['$', '$'], ['\\(', '\\)']]
#         processEscapes: true
#       options:
#         skipHtmlTags: ['script', 'noscript', 'style', 'textarea', 'pre']
#     myst_enable_extensions:
#       - amsmath  # Enable AMS math features
#       - dollarmath