name: Build and Deploy Jupyter Book

on:
  push:
    branches:
      - main  # Deploy when pushing to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out the repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
        
    - name: Install Jupyter Book
      run: |
        pip install -r requirements.txt
    
    - name: Build Jupyter Book
      run: |
        jupyter-book build . --all
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _build/html
        publish_branch: gh-pages  # Specify branch if not default
